const en = {
  products: 'products',
  about: 'about',
  contact: 'contact',
  sign_in: 'sign in',
  sign_up: 'sign up',
  new_product: 'new product',
  management: 'management',
  categories: 'categories',
  sign_out: 'Sign out',
  sum: 'Sum',
  paid_delivery: 'Paid delivery',
  under: 'under €',
  total: 'Total',
  order: 'order',
  city: 'city',
  street: 'street',
  house: 'house',
  apt: 'apartment',
  name: 'name',
  surname: 'surname',
  phone: 'phone',
  add_new_address: 'add new address',
  proceed_to_payment: 'go to payment',
  contact_us: 'contact us',
  email: 'email',
  message: 'message',
  send_message: 'send message',
  buy: 'buy',
  add_to_cart: 'add to cart',
  nutritional_info: 'nutritional info',
  g_contains: '100g contains',
  energy_content: 'energy content',
  fat: 'fat',
  of_which_saturated_fat: 'of which saturated fat',
  carbohydrates: 'carbohydrates',
  of_which_sugars: 'of which sugars',
  fiber: 'fiber',
  protein: 'protein',
  salt: 'salt',
  EAN_code: 'EAN code',
  about_us: 'about us',
  values: 'our values',
  nature: 'nature',
  people: 'people',
  quality: 'quality',
  how_products_are_made: "how flora bakery's products are made",
  product: 'product',
  category: 'category',
  select_existing_categories: 'Select existing categories',
  select_existing_products: 'Select existing products',
  add_category: 'Add a category',
  add_new_category: 'Add a new category',
  product_name: 'name',
  image_url: 'image url',
  cancel: 'cancel',
  add: 'add',
  or: 'or',
  add_new_product: 'Add a new product',
  add_product: 'Add a product',
  description: 'description',
  ingredients: 'ingredients',
  weight: 'weight',
  in_grams: 'in grams',
  price: 'price (cents)',
  in_cents: 'cents',
  add_to_all: "Add to category 'all'",
  add_to_new: "Add to category 'new'",
  accept_order: 'Accept order?',
  accept: 'accept',
  refuse: 'refuse',
  ready_for_delivery: 'Ready for delivery?',
  ready: 'ready',
  out_for_delivery: 'Out for delivery?',
  deliver: 'deliver',
  delivery_completed: 'Delivery completed?',
  completed: 'completed',
  order_status: {
    placed: 'placed',
    accepted: 'accepted',
    refused: 'refused',
    packing: 'packing',
    waitingForDelivery: 'waiting for delivery',
    delivering: 'delivering',
    completed: 'completed',
  },
  last_modified_by: 'last modified by',
  confirm_delete: 'Are you sure you want to delete this product?',
  confirm_save_changes: 'Are you sure you want to save these changes?',
  save_changes: 'save changes',
  discard_changes: 'discard changes',
  edit_product: 'edit product',
  delete_product: 'delete product',
  empty_cart: 'Your shopping cart is empty.',
  orders: 'Orders',
  username: 'username',
  password: 'password',
  about_text: [
    'Flora Bakery was founded back in the 1990s when it put its first homemade loaf of white bread on the festive table at Christmas time. The bakery’s name has historical origins. Before focusing on making delicious baked products and pastries, the owners grew flowers. This inspired them to give their next line of business a name connected with nature. The bakery was named Flora.',
    'In 2008, Flora opened its new EU standard production plan in Krimulda Parish in a mythical place named Ragana. Here all products are produced at one site. However, in this modern bakery, our greatest asset is still the fact that our products are handcrafted, which we combine with years of knowledge of how to bake the best quality products.',
    'In April 2012, Flora Bakery received a BIO product production certificate.',
    'Fragrant, organic, natural ingredients are among the core values of Flora Bakery, whereby nature and its colours are the source of inspiration, which created the Flora Bakery. Picture the scenery, Latvia’s blossoming meadows adorned by playful red poppies and golden ears, radiating in the glowing sun. Just as an perfumer takes the most captivating aromas to create perfumes, we seek the highest quality ingredients as well as unique herbs and spices. Flora products are made nurturing the knowledge and know-how of our expert bakers. We offer our customers an intimate bouquet of flavour created right here in the picturesque Latvian parish of Krimulda. May the floral delights blossom on your table!',
  ],
  create: 'create',
  verify_email: 'Verify email',
  verification_instructions:
    'Open your email and follow the instructions to verify your email and start shopping',
  password_must: 'Password must',
  password_8_chars: 'Be at least 8 characters long',
  password_contain_digit: 'Contain at least one digit',
  password_contain_special: 'Contain at least one of !@#$%^&*',
  password_contain_letter: 'Contain at least one letter',
  toast_all_fields_required: 'All fields are required',
  toast_address_added: 'The address has been added',
  toast_sending: 'Sending',
  toast_success: 'Success!',
  toast_failed: 'Failed to do the thing',
  toast_order_successful: 'Your order has been placed!',
  toast_unauthorized: 'You are not allowed to do that',
  email_required: 'Email is required',
  password_required: 'Password is required',
  email_already_used: 'This email is already registered',
  already_have_account: 'Already have an account? Sign in.',
  dont_have_account: "Don't have an account yet? Sign up here.",
  invalid_credentials: 'Email or password is incorrect',
  with_VAT: 'VAT incl.',
  expiration_time: 'Product is good for',
  after_opening: 'After opening use within',
  days: 'days',
  months: 'months',
  save: 'Save changes',
  new: 'New product',
  vegan: 'Vegan',
  high_protein: 'High in protein',
  high_fiber: 'High in fiber',
  handmade: 'Handmade',
  no_added_yeast: 'No added yeast',
  no_conservants: 'No added conservants',
  vitamin_d: 'Source of vitamin D',
  iodine: 'Source of iodine',
  d3: 'vitamin D3',
  toast_changes_saved: 'Changes have been saved!',
  toast_product_created: 'The product has been created!',
  discounts: 'Discounts',
  found_categories: 'Found categories',
  found_products: 'Found products',
  create_discount: 'Discount',
  remove_discount: 'Remove discount',
  discount_price: 'Discounted price',
  start_date: 'Start date',
  end_date: 'End date',
  without_vat_cents: 'without VAT, in cents',
  confirm_remove_discount: 'Are you sure you want to remove the discount?',
  toast_discount_created: 'The discount has been created!',
  toast_discount_removed: 'The discount has been removed!',
  eu_projects: 'EU Projects',
  distance_agreement: 'Distance agreement',
  sales: 'Sales',
  production: 'Production',
  sales_manager: 'Sales Manager',
  deputy_sales_manager: 'Deputy Sales Manager',
  export_manager: 'Export Manager',
  bread_manager: 'Bread Production and Quality Manager',
  pastry_manager: 'Pastry Production and Quality Manager',
  currently_unavailable: 'Out of stock',
  forgot_password: 'Forgot your password? Click here.',
  reset_password: 'Reset password',
  send_reset_instructions: 'Send reset email',
  toast_reset_email_sent: 'Password reset email has been sent!',
  confirm_password: 'Confirm password',
  password_match: 'Passwords must match',
  email_not_registered:
    'There is no account associated with this email address',
  toast_password_reset: 'Password has been changed',
  privacy_policy: 'Privacy policy',
  profile: 'Account',
  previous_orders: 'Previous orders',
  change_password: 'Change password',
  account_information: 'Personal information',
  addresses: 'Addresses',
  previous_password: 'Previous password',
  previous_password_required: 'Previous password is required',
  previous_password_incorrect: 'Previous password is wrong',
  edit: 'Edit',
  delete: 'Delete',
  toast_address_edited: 'The address has been edited',
  toast_address_deleted: 'The address has been deleted',
  confirm_delete_address: 'Are you sure you want to delete this address?',
  save_short: 'Save',
  when_buying: 'When buying',
  or_more: 'or more',
  delete_account: 'Delete account',
  confirm_delete_account:
    'Are you sure you want to delete your account? The action is irreversible and you will not be able to access your account anymore.',
  toast_account_deleted: 'Account has been deleted',
  cart: 'Cart',
  delivery: 'Delivery',
  payment: 'Payment',
  pick_up_from_flora: 'Pick up at the bakery',
  next_working_day: 'Next workday',
  pickup_point: 'DPD pickup point',
  courrier: 'Courrier delivery',
  pickup_point_delivery_time: '2 - 3 days',
  courrier_delivery_time: '2 - 3 days',
  select_point: 'Select pickup point',
  to_delivery: 'Choose delivery',
  to_payment: 'Go to payment',
  toast_select_delivery_method: 'Select a delivery method!',
  toast_select_pickup_point: 'Select a pickup point!',
  toast_select_address: 'Select an address!',
}

export default en
