const en = {
  products: 'products',
  about: 'about',
  contact: 'contact',
  sign_in: 'sign in',
  sign_up: 'sign up',
  new_product: 'management',
  sign_out: 'sign out',
  sum: 'sum',
  paid_delivery: 'paid delivery',
  under_30: 'under €30',
  total: 'total',
  order: 'order',
  city: 'city',
  street: 'street',
  house: 'house',
  apt: 'apartment',
  name: 'name',
  surname: 'surname',
  phone: 'phone',
  add_new_address: 'add new address',
  proceed_to_payment: 'go to payment',
  contact_us: 'contact us',
  email: 'email',
  message: 'message',
  send_message: 'send message',
  buy: 'buy',
  add_to_cart: 'add to cart',
  nutritional_info: 'nutritional info',
  g_contains: '100g contains',
  energy_content: 'energy content',
  fat: 'fat',
  of_which_saturated_fat: 'of which saturated fat',
  carbohydrates: 'carbohydrates',
  of_which_sugars: 'of which sugars',
  fiber: 'fiber',
  protein: 'protein',
  salt: 'salt',
  EAN_code: 'EAN code',
  about_us: 'about us',
  values: 'our values',
  nature: 'nature',
  people: 'people',
  quality: 'quality',
  product: 'product',
  category: 'category',
  select_existing_categories: 'Select existing categories',
  select_existing_products: 'Select existing products',
  add_category: 'Add a category',
  add_new_category: 'Add a new category',
  product_name: 'name',
  image_url: 'image url',
  cancel: 'cancel',
  add: 'add',
  or: 'or',
  add_new_product: 'Add a new product',
  add_product: 'Add a product',
  description: 'description',
  ingredients: 'ingredients',
  weight: 'weight',
  in_grams: 'in grams',
  price: 'price (cents)',
  add_to_all: "Add to category 'all'",
  add_to_new: "Add to category 'new'",
  accept_order: 'Accept order?',
  accept: 'accept',
  refuse: 'refuse',
  ready_for_delivery: 'Ready for delivery?',
  ready: 'ready',
  out_for_delivery: 'Out for delivery?',
  deliver: 'deliver',
  delivery_completed: 'Delivery completed?',
  completed: 'completed',
  order_status: {
    placed: 'placed',
    accpeted: 'accepted',
    refused: 'refused',
    packing: 'packing',
    waitingForDelivery: 'waiting for delivery',
    delivering: 'delivering',
    completed: 'completed',
  },
  last_modified_by: 'last modified by',
  confirm_delete: 'Are you sure you want to delete this product?',
  confirm_save_changes: 'Are you sure you want to save these changes?',
  save_changes: 'save changes',
  discard_changes: 'discard changes',
  edit_product: 'edit product',
  delete_product: 'delete product',
  empty_cart: 'Your shopping cart is empty.',
  orders: 'orders',
  username: 'username',
  password: 'password',
}

export default en
