const lv = {
  products: 'produkti',
  about: 'par mums',
  contact: 'kontakti',
  sign_in: 'ienākt',
  sign_up: 'reģistrēties',
  new_product: 'jauns produkts',
  management: 'pārvaldīt',
  categories: 'kategorijas',
  sign_out: 'iziet',
  sum: 'kopā',
  paid_delivery: 'maksas piegāde',
  under_30: 'zem €30',
  total: 'pavisam',
  order: 'pasūtīt',
  city: 'pilsēta',
  street: 'iela',
  house: 'māja',
  apt: 'dzīvoklis',
  name: 'vārds',
  surname: 'uzvārds',
  phone: 'tālrunis',
  add_new_address: 'pievienot adresi',
  proceed_to_payment: 'uz apmaksu',
  contact_us: 'sazinies ar mums',
  email: 'e-pasts',
  message: 'vēstule',
  send_message: 'nosūtīt',
  buy: 'pirkt',
  add_to_cart: 'pievienot grozam',
  nutritional_info: 'uzturvērtība',
  g_contains: '100g produkta satur',
  energy_content: 'enerģētiskā vērtība',
  fat: 'tauki',
  of_which_saturated_fat: 'tostarp piesātinātās taukskābes',
  carbohydrates: 'ogļhidrāti',
  of_which_sugars: 'tostarp cukuri',
  fiber: 'šķiedrvielas',
  protein: 'olbaltumvielas',
  salt: 'sāls',
  EAN_code: 'EAN kods',
  about_us: 'par mums',
  values: 'vērtības kuras godājam',
  nature: 'daba',
  people: 'cilvēks',
  quality: 'kvalitāte',
  how_products_are_made: 'KĀ TOP MAIZNĪCAs FLORA PRODUKTI?',
  product: 'produkts',
  category: 'kategorija',
  select_existing_categories: 'Izvēlēties no esošām kategorijām',
  select_existing_products: 'Izvēlēties no esošiem produktiem',
  add_category: 'Pievienot kategoriju',
  add_new_category: 'Izveidot jaunu kategoriju',
  product_name: 'nosaukums',
  image_url: 'saite uz attēlu',
  cancel: 'atcelt',
  add: 'pievienot',
  or: 'vai',
  add_new_product: 'Izveidot jaunu produktu',
  add_product: 'Pievienot produktu',
  description: 'apraksts',
  ingredients: 'sastāvdaļas',
  weight: 'svars',
  in_grams: 'gramos',
  price: 'cena (centos)',
  in_cents: 'centos',
  add_to_all: "Pievienot 'all' kategorijai",
  add_to_new: "Pievienot 'new' kategorijai",
  accept_order: 'Pieņemt pasūtījumu?',
  accept: 'pieņemt',
  refuse: 'noraidīt',
  ready_for_delivery: 'Gatavs piegādāšanai?',
  ready: 'gatavs',
  out_for_delivery: 'Nosūtīt?',
  deliver: 'sūtīt',
  delivery_completed: 'Piegādāts?',
  completed: 'piegādāts',
  order_status: {
    placed: 'pasūtīts',
    accepted: 'pieņemts',
    refused: 'atteikts',
    packing: 'tiek gatavots',
    waitingForDelivery: 'gaida piegādi',
    delivering: 'tiek piegādāts',
    completed: 'piegādāts',
  },
  last_modified_by: 'pēdējoreiz mainījis',
  confirm_delete: 'Vai tiešām dzēst šo produktu?',
  confirm_save_changes: 'Vai tiešām saglabāt šīs izmaiņas?',
  save_changes: 'saglabāt izmaiņas',
  discard_changes: 'atcelt izmaiņas',
  edit_product: 'rediģēt produktu',
  delete_product: 'dzēst produktu',
  empty_cart: 'Pirkumu grozs ir tukšs.',
  orders: 'pasūtījumi',
  username: 'lietotājvārds',
  password: 'parole',
  about_text_top:
    'Stāsts par mums ir himna roku darbam un gadu gaitā uzkrātām zināšanām, kā radīt kvalitatīvus un veselīgus gardumus. Tā ir himna Latvijas zemei, kas ik gadu vēlīgi pieņem zeltainos graudus un dāsni apbalvo mūs ar ražu. Tas ir stāsts par augsta līmeņa profesionāļiem, kas pašaizliedzīgi strādā, lai ikviens varētu celt savā galdā vislabāko – gan Latvijā, gan tālu pāri robežām. Stāsts par mums ir arī stāsts par skatu nākotnē un lieliem mērķiem.',
  about_text: [
    {
      title: 'MODERNA UN JAUDĪGA RAŽOTNE',
      text: 'Mēs lepojamies ar mūsdienīgu Eiropas Savienības līmenim atbilstošu ražotni, kurā ik gadu tiek saražotas ap 1000 tonnu produkcijas – maize, cepumi, piparkūkas un citi konditorejas izstrādājumi. ',
    },
    {
      title: 'LIELĀKAIS DARBA DEVĒJS NOVADĀ',
      text: 'Šobrīd uzņēmumā strādā 100 darbinieki – un mūsu skaits arvien pieaug. Mēs esam atvērta, zinātkāra un draudzīga komanda, ko veido arī ģimenes, turklāt dažiem šī ir bijusi vienīgā darba vieta. ',
    },
    {
      title: 'TĀLREDZĪGA DOMĀŠANA',
      text: 'Mēs esam noenkurojušies pie lielākā un vecākā Latvijas nacionālā parka robežas – Krimuldas pagastā, tāpēc likumsakarīgi, ka domājam tālredzīgi un saimniekojam dabai draudzīgi. Esam ieguvuši Bioloģiski ražotu produktu sertifikātu Nr. 05-001-2012/P-02, izmantojam organiski audzētas izejvielas, kā arī piedāvājam produktus vegāniem.',
    },
  ],
  nature_text:
    'Līdzsvars un harmonija dabā mūs fascinē un veldzē. Iedvesmo jauniem mērķiem un virsotnēm. Daba mūs baro un atjauno. Mēs esam atbildīgi par šo mantojumu un aicinām tādiem būt arī citiem.',
  people_text:
    'Mēs godājam kompetentu, priecīgu un meistarīgu darbinieku mijiedarbībā ar zinošu, pārliecinātu un apmierinātu klientu. Mēs ticam, ka, dzīvojot sabiedrībā, kur cilvēks ir vērtība, mēs atstāsim labāku pasauli saviem bērniem.',
  quality_text:
    'Kvalitāte it visā, kam ķeramies klāt. Ko veidojam un radām. Ikkatrā maizes klaipā un cepuma gabaliņā. Un attiecībās. Kvalitāte ik uz soļa, bez kompromisiem. Tas nebūtu iespējams, ja mēs negodātu šo principu – labāk mazāk, bet augstvērtīgi, nekā pavirši un daudz.',
  create: 'izveidot',
}

export default lv
