const lv = {
  products: 'produkti',
  about: 'par mums',
  contact: 'kontakti',
  sign_in: 'ienākt',
  sign_up: 'reģistrēties',
  new_product: 'pārvaldīt',
  sign_out: 'iziet',
  sum: 'kopā',
  paid_delivery: 'maksas piegāde',
  under_30: 'zem €30',
  total: 'pavisam',
  order: 'pasūtīt',
  city: 'pilsēta',
  street: 'iela',
  house: 'māja',
  apt: 'dzīvoklis',
  name: 'vārds',
  surname: 'uzvārds',
  phone: 'tālrunis',
  add_new_address: 'pievienot adresi',
  proceed_to_payment: 'uz apmaksu',
  contact_us: 'sazienies ar mums',
  email: 'e-pasts',
  message: 'vēstule',
  send_message: 'nosūtīt',
  buy: 'pirkt',
  add_to_cart: 'pievienot grozam',
  nutritional_info: 'uzturvērtība',
  g_contains: '100g produkta satur',
  energy_content: 'enerģētiskā vērtība',
  fat: 'tauki',
  of_which_saturated_fat: 'tostarp piesātinātās taukskābes',
  carbohydrates: 'ogļhidrāti',
  of_which_sugars: 'tostarp cukuri',
  fiber: 'šķiedrvielas',
  protein: 'olbaltumvielas',
  salt: 'sāls',
  EAN_code: 'EAN kods',
  about_us: 'par mums',
  values: 'vērtības kuras godājam',
  nature: 'daba',
  people: 'cilvēks',
  quality: 'kvalitāte',
  product: 'produkts',
  category: 'kategorija',
  select_existing_categories: 'Izvēlēties no esošām kategorijām',
  select_existing_products: 'Izvēlēties no esošiem produktiem',
  add_category: 'Pievienot kategoriju',
  add_new_category: 'Izveidot jaunu kategoriju',
  product_name: 'nosaukums',
  image_url: 'saite uz attēlu',
  cancel: 'atcelt',
  add: 'pievienot',
  or: 'vai',
  add_new_product: 'Izveidot jaunu produktu',
  add_product: 'Pievienot produktu',
  description: 'apraksts',
  ingredients: 'sastāvdaļas',
  weight: 'svars',
  in_grams: 'gramos',
  price: 'cena (centos)',
  add_to_all: "Pievienot 'all' kategorijai",
  add_to_new: "Pievienot 'new' kategorijai",
  accept_order: 'Pieņemt pasūtījumu?',
  accept: 'pieņemt',
  refuse: 'noraidīt',
  ready_for_delivery: 'Gatavs piegādāšanai?',
  ready: 'gatavs',
  out_for_delivery: 'Nosūtīt?',
  deliver: 'sūtīt',
  delivery_completed: 'Piegādāts?',
  completed: 'piegādāts',
  order_status: {
    placed: 'pasūtīts',
    accpeted: 'pieņemts',
    refused: 'atteikts',
    packing: 'tiek gatavots',
    waitingForDelivery: 'gaida piegādi',
    delivering: 'tiek piegādāts',
    completed: 'piegādāts',
  },
  last_modified_by: 'pēdējoreiz mainījis',
  confirm_delete: 'Vai tiešām dzēst šo produktu?',
  confirm_save_changes: 'Vai tiešām saglabāt šīs izmaiņas?',
  save_changes: 'saglabāt izmaiņas',
  discard_changes: 'atcelt izmaiņas',
  edit_product: 'rediģēt produktu',
  delete_product: 'dzēst produktu',
  empty_cart: 'Pirkumu grozs ir tukšs.',
  orders: 'pasūtījumi',
  username: 'lietotājvārds',
  password: 'parole',
}

export default lv
